version = 1

test_patterns = ["testing.py"]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"