# Currently supported categories and subcategories, changing these will be reflected in the web app
search_categories = {
    "Computer Science": [
        "Artificial Intelligence",
        "Computer Vision",
        "Natural language processing",
        "Databases",
        "Distributed, Parallel, and Cluster Computing",
        "Data Structures and Algorithms",
        "Computer Science and Game Theory",
        "Machine Learning",
        "Robotics",
        "Software Engineering",
    ],
    "Mathmatics": [
        "Combinatorics",
        "Dynamical Systems",
        "Numerical Analysis",
        "Number Theory",
        "Probability",
        "Quantum Algebra",
        "Logic",
    ],
    "Biology": [
        "Biomolecules",
        "Genomics",
        "Neurons and Cognition",
        "Subcellular Processes",
        "Quantitative Biological Methods",
    ],
    "Physics": [
        "Astrophysics",
        "Condensed matter",
        "General relativity and quantum cosmology",
        "High energy physics",
        "Mathematical physics",
        "Nonlinear sciences",
        "Nuclear experiment",
        "Nuclear theory",
        "Quantum physics",
    ],
    "Statistics": [
        "Statistics Applications",
        "Computational Statistics",
        "Statistics Methodology",
        "Statistics Theory",
    ],
}
